function gasPhaseNameList = gasphasenamelist
gasPhaseNameList = {'N2_O1D -> O + N2 ->';...
'O2_O1D -> O + O2 ->';...
'O_O2_M -> O3 + M';...
'O3_O -> 2*O2';...
'O1D_O3 -> 2*02';...
'O_O_M -> O2 + M';...
'NO_HO2 -> NO2 + OH';...
'NO_O3 -> NO2 + O2';...
'NO2_O -> NO + O2';...
'NO2_O3 -> NO3 + O2';...
'NO3_NO -> 2*NO2';...
'NO3_O -> NO2 + O2';...
'NO3_OH -> HO2 + NO2';...
'NO3_HO2 -> OH + NO2 +O2';...
'O1D_N2Oa -> 2*NO';...
'O1D_N2Ob -> N2 + O2';...
'CH3O2_NO -> CH3O + NO2';...
'NO3_CH2O -> CO + HO2 + HNO3';...
'HNO3_OH -> NO3 + H2O';...
'NO2_HO2_M -> HO2NO2 + M';...
'NO_O_M -> NO2 + M';...
'NO2_NO3_M -> N2O5 + M';...
'NO2_O_M -> NO3 + M';...
'NO2_OH_M -> HNO3 + M';...
'N2O5_M -> NO2 + NO3 + M';...
'H_O3 -> OH + O2';...
'OH_O -> H + O2';...
'OH_O3 -> HO2 + O2';...
'OH_HO2 -> H2O + O2';...
'OH_OH -> H2O + O';...
'OH_H2 -> H2O + H';...
'OH_H2O2 -> H2O + HO2';...
'OH_CH2O -> CO + H2O + H';...
'HO2_CH2O -> HOCHOO';...
'HO2_O -> OH + O2';...
'HO2_O3 -> OH + 2*O2';...
'H2O_O1D -> 2*OH';...
'H2_O1D -> H + OH';...
'CH4_O1D -> CH3O2 + OH';...
'HO2_HO2 -> H2O2 + O2';...
'HO2NO2_OH -> H2O + NO2 + O2';...
'HO2NO2_M -> HO2 + NO2 + M';...
'CH4_OH -> CH3O2 + H2O';...
'H2O2_O -> OH + HO2';...
'H_O2_M -> HO2 + M';...
'OH_OH_M -> H2O2 + M';...
'OH_CO_Ma -> CO2 + HO2';...
'OH_CO_Mb -> H + CO2 + M';...
'SO2_OH_M -> HSO3 + M';...
'CL_O3 -> CLO + O2';...
'CL_H2 -> HCL + H';...
'CL_H2O2 -> HCL + HO2';...
'CL_HO2a -> HCL + O2';...
'CL_HO2b -> OH + CLO';...
'CL_CH2O -> HCL + HO2 + CO';...
'CL_CH4 -> CH3O2 + HCL';...
'CLO_O -> CL + O2';...
'CLO_OHa -> CL + HO2';...
'CLO_OHb -> HCL + O2';...
'CLO_HO2 -> O2 + HOCL';...
'CLO_CH3O2 -> CL + HO2 + CH2O';...
'CLO_NO -> NO2 + CL';...
'CLO_CLOa -> 2*CL + O2';...
'CLO_CLOb -> CL2 + O2';...
'CLO_CLOc -> CL + OCLO';...
'HCL_OH -> H2O + CL';...
'HCL_O1D -> CL + OH';...
'HCL_O -> CL + OH';...
'HOCL_O -> CLO + OH';...
'HOCL_CL -> HCL + CLO';...
'HOCL_OH -> H2O + CLO';...
'CLONO2_O -> CLO + NO3';...
'CLONO2_OH -> HOCL + NO3';...
'CLONO2_CL -> CL2 + NO3';...
'BR_O3 -> BRO + O2';...
'BR_HO2 -> HBR + O2';...
'BR_CH2O -> HBR + HO2 + CO';...
'BRO_O -> BR + O2';...
'BRO_OH -> BR + HO2';...
'BRO_HO2 -> HOBR + O2';...
'BRO_NO -> BR + NO2';...
'BRO_CLOa -> BR + OCLO';...
'BRO_CLOb -> BR + CL + O2';...
'BRO_CLOc -> BRCL + O2';...
'BRO_BRO -> 2*BR + O2';...
'HBR_OH -> BR + H2O';...
'HBR_O1D -> BR + OH';...
'HOBR_O -> BRO + OH';...
'BRONO2_O -> BRO + NO3';...
'BR_OCLO -> BRO + CLO';...
'CLO_NO2_M -> CLONO2 + M';...
'CLO_CLO_M -> CL2O2 + M';...
'CL2O2_M -> 2*CLO + M';...
'BRO_NO2_M -> BRONO2 + M'};

end
