function photoNamelist = TUVnamelist

photoNamelist = {'O2 -> O + O';...                             
'O3 -> O2 + O(1D)';...                        
'O3 -> O2 + O(3P)';...                        
'HO2 -> OH + O';...                           
'H2O2 -> 2 OH';...                            
'NO2 -> NO + O(3P)';...                       
'NO3 -> NO + O2';...                          
'NO3 -> NO2 + O(3P)';...                      
'N2O -> N2 + O(1D)';...                       
'N2O5 -> NO3 + NO + O(3P)';...                
'N2O5 -> NO3 + NO2';...                       
'HNO2 -> OH + NO';...                         
'HNO3 -> OH + NO2';...                        
'HNO4 -> HO2 + NO2';...                       
'NO3-(aq) -> NO2(aq) + O-';...                
'NO3-(aq) -> NO2-(aq) + O(3P)';...            
'NO3-(aq) with qy=1';...                      
'CH2O -> H + HCO';...                         
'CH2O -> H2 + CO';...                         
'CH3CHO -> CH3 + HCO';...                     
'CH3CHO -> CH4 + CO';...                      
'CH3CHO -> CH3CO + H';...                     
'C2H5CHO -> C2H5 + HCO';...                   
'CH3OOH -> CH3O + OH';...                     
'HOCH2OOH -> HOCH2O. + OH';...                
'CH3ONO2 -> CH3O + NO2';...                   
'CH3(OONO2) -> CH3(OO) + NO2';...             
'CH3CH2ONO2 -> CH3CH2O + NO2';...             
'C2H5ONO2 -> C2H5O + NO2';...                 
'n-C3H7ONO2 -> C3H7O + NO2';...               
'1-C4H9ONO2 -> 1-C4H9O + NO2';...             
'2-C4H9ONO2 -> 2-C4H9O + NO2';...             
'CH3CHONO2CH3 -> CH3CHOCH3 + NO2';...         
'CH2(OH)CH2(ONO2) -> CH2(OH)CH2(O.) + NO2';...
'CH3COCH2(ONO2) -> CH3COCH2(O.) + NO2';...    
'C(CH3)3(ONO2) -> C(CH3)3(O.) + NO2';...      
'C(CH3)3(ONO) -> C(CH3)3(O) + NO';...         
'CH3CO(OONO2) -> CH3CO(OO) + NO2';...         
'CH3CO(OONO2) -> CH3CO(O) + NO3';...          
'CH3CH2CO(OONO2) -> CH3CH2CO(OO) + NO2';...   
'CH3CH2CO(OONO2) -> CH3CH2CO(O) + NO3';...    
'CH2=CHCHO -> Products';...                   
'CH2=C(CH3)CHO -> Products';...               
'CH3COCH=CH2 -> Products';...                 
'HOCH2CHO -> CH2OH + HCO';...                 
'HOCH2CHO -> CH3OH + CO';...                  
'HOCH2CHO -> CH2CHO + OH';...                 
'CH3COCH3 -> CH3CO + CH3';...                 
'CH3COCH2CH3 -> CH3CO + CH2CH3';...           
'CH2(OH)COCH3 -> CH3CO + CH2(OH)';...         
'CH2(OH)COCH3 -> CH2(OH)CO + CH3';...         
'CHOCHO -> HCO + HCO';...                     
'CHOCHO -> H2 + 2CO';...                      
'CHOCHO -> CH2O + CO';...                     
'CH3COCHO -> CH3CO + HCO';...                 
'CH3COCOCH3 -> Products';...                  
'CH3COOH -> CH3 + COOH';...                   
'CH3CO(OOH) -> Products';...                  
'CH3COCO(OH) -> Products';...                 
'(CH3)2NNO -> Products';...                   
'CF2O -> Products';...                        
'Cl2 -> Cl + Cl';...                          
'ClO -> Cl + O(1D)';...                       
'ClO -> Cl + O(3P)';...                       
'ClOO -> Products';...                        
'OClO -> Products';...                        
'ClOOCl -> Cl + ClOO';...                     
'HCl -> H + Cl';...                           
'HOCl -> HO + Cl';...                         
'NOCl -> NO + Cl';...                         
'ClNO2 -> Cl + NO2';...                       
'ClONO -> Cl + NO2';...                       
'ClONO2 -> Cl + NO3';...                      
'ClONO2 -> ClO + NO2';...                     
'CCl4 -> Products';...                        
'CH3OCl -> CH3O + Cl';...                     
'CHCl3 -> Products';...                       
'CH3Cl -> Products';...                       
'CH3CCl3 -> Products';...                     
'CCl2O -> Products';...                       
'CClFO -> Products';...                       
'CCl3F (CFC-11) -> Products';...              
'CCl2F2 (CFC-12) -> Products';...             
'CF2ClCFCl2 (CFC-113) -> Products';...        
'CF2ClCF2Cl (CFC-114) -> Products';...        
'CF3CF2Cl (CFC-115) -> Products';...          
'CHClF2 (HCFC-22) -> Products';...            
'CF3CHCl2 (HCFC-123) -> Products';...         
'CF3CHFCl (HCFC-124) -> Products';...         
'CH3CFCl2 (HCFC-141b) -> Products';...        
'CH3CF2Cl (HCFC-142b) -> Products';...        
'CF3CF2CHCl2 (HCFC-225ca) -> Products';...    
'CF2ClCF2CHFCl (HCFC-225cb) -> Products';...  
'Br2 -> Br + Br';...                          
'BrO -> Br + O';...                           
'HOBr -> OH + Br';...                         
'BrNO -> Br + NO';...                         
'BrONO -> Br + NO2';...                       
'BrONO -> BrO + NO';...                       
'BrNO2 -> Br + NO2';...                       
'BrONO2 -> BrO + NO2';...                     
'BrONO2 -> Br + NO3';...                      
'BrCl -> Br + Cl';...                         
'CH3Br -> Products';...                       
'CHBr3 -> Products';...                       
'CF2Br2 (Halon-1202) -> Products';...         
'CF2BrCl (Halon-1211) -> Products';...        
'CF3Br (Halon-1301) -> Products';...          
'CF2BrCF2Br (Halon-2402) -> Products';...     
'I2 -> I + I';...                             
'IO -> I + O';...                             
'IOH -> I + OH';...                           
'perfluoro 1-iodopropane -> products'};


end
